"""new table

Revision ID: d5e02f198a40
Revises: 
Create Date: 2020-02-01 19:27:46.056613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e02f198a40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sn', sa.Integer(), nullable=False),
    sa.Column('pin', sa.String(length=140), nullable=False),
    sa.Column('request_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pin'),
    sa.UniqueConstraint('sn')
    )
    op.create_index(op.f('ix_register_request_time'), 'register', ['request_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_register_request_time'), table_name='register')
    op.drop_table('register')
    # ### end Alembic commands ###
